### ISSUE TITLE
通过什么方式快速获取到快递100的API

### ISSUE THREAD

**Issue by uddmorningsun** [7sDream/kd100#2]
Hello，想知道下您是如何知道快递100的API的？是以什么方式获取的？
例如（在代码/kd100.py）：
> GUESS = 'http://m.kuaidi100.com/autonumber/auto?{0}'
> QUERY = 'http://m.kuaidi100.com/query?{0}'

我发现了可以申请API通过 [快递接口](https://m.kuaidi100.com/openapi/applypoll.jsp)，但是相比较，没有你在代码中所使用的API简单，因此想知道下你获取API的方式是什么？

谢谢！

**Comment by 7sDream** [comment]
这个项目老早了……我也不太记得了……我想想啊

好像是在某个移动版的快递 100 的查询页上，然后 Chrome F12 了一下找到的……

当年具体是哪个页面我也没存，一时间可能没法再找到……Sorry

我尽量帮你回忆下吧~找到了告诉你

**Comment by uddmorningsun** [comment]
Really Thanks！ 期待好消息 @7sDream

**Comment by 7sDream** [comment]
@memory-yancy 

https://m.kuaidi100.com/

应该是这个，F12 一下就能看到 API 了
